- name: "undeploy layer"
  hosts: localhost
  tasks:
    # Common
    - name: undeploy kw-ingress module
      include_tasks: "../modules/kw-ingress/playbook/undeploy.yaml"

    #Platform specific
    - name: check for platform support
      stat:
        path: "./platforms/{{ ansible_facts['os_family'] }}_{{ ansible_facts['architecture']}}/undeploy.yaml"
      register: file_exists

    - name: error if platform tasks doesn't exists
      fail:
        msg: "the platform {{ ansible_facts['os_family'] }} on {{ ansible_facts['architecture']}} isn't supported (yetà"
      when: "not file_exists.stat.exists"

    - name: uninstall layer for {{ ansible_facts['os_family'] }} on {{ ansible_facts['architecture']}} platform
      include_tasks: "./platforms/{{ ansible_facts['os_family'] }}_{{ ansible_facts['architecture']}}/undeploy.yaml"
