- name: check for kind
  shell: which kind
  failed_when: no
  changed_when: no
  register: kind_present

- name: check for cluster
  command:
    argv:
      - kind
      - get
      - clusters
  register: clusters_list
  changed_when: no
  when:
    - "'kind' in kind_present.stdout"
- name: uninstall {{ module_name }} helm chart
  command:
    argv:
      - helm
      - uninstall
      - --kube-context
      - "{{ k8s_context }}"
      - --namespace
      - "{{ namespace }}"
      - "{{ module_name }}"
  register: uninstall_helm
  when:
    - "'kind' in kind_present.stdout"
    - "env_name in clusters_list.stdout"
  failed_when:
    - "'release: not found' not in uninstall_helm.stderr"
    - "'Kubernetes cluster unreachable:' not in uninstall_helm.stderr"
    - "'uninstalled' not in uninstall_helm.stdout"

- name: delete {{ module_name }} namespace
  k8s:
    state: absent
    context: "{{ k8s_context }}"
    api_version: v1
    kind: Namespace
    name: "{{ namespace }}"
  when:
    - "'kind' in kind_present.stdout"
    - "env_name in clusters_list.stdout"
    - "'Kubernetes cluster unreachable:' not in uninstall_helm.stderr"

- name: wait for namespace for {{ module_name }} deletion completed
  command:
    argv:
      - kubectl
      - wait
      - --context
      - "{{ k8s_context }}"
      - --for=delete
      - namespace/{{ namespace }}
      - --timeout=90s
  register: wait_delete
  when:
    - "'kind' in kind_present.stdout"
    - "env_name in clusters_list.stdout"
    - "'Kubernetes cluster unreachable:' not in uninstall_helm.stderr"

  failed_when:
    - "not 'not found' in wait_delete.stderr"
    - "not 'condition met' in wait_delete.stdout"
