- name: "deploy {{ module_name }} module"
  include_role:
    name: kws_deploy_module
  vars:
    home_path: "{{ datas_host.root_path }}"
    docker_machine_name: "{{ k8s_host.docker_machine_name }}"
    k8s_context: "{{ k8s_cluster.k8s_context }}"
    namespace: ingress-nginx
    module_name: kw-ingress-nginx
    chart_path: "{{ module_path }}/chart/"
    helm_values: 
      dummy: false

- name: waiting for nginx ingress ready
  command:
    argv:
      - kubectl
      - wait
      - --context
      - "{{ k8s_cluster.k8s_context }}"
      - --namespace
      - ingress-nginx
      - --for=condition=ready
      - pod
      - --selector=app.kubernetes.io/component=controller
      - --timeout=90s
  environment:
    HOME: "{{ datas_host.root_path }}"
