- name: extracting docker-machine env vars
  shell: "sh ./roles/common/files/extract-docker-machine-vars.sh {{ registry_host.docker_machine_name }}"
  register: docker_machine_env_exports
  changed_when: no
  environment:
    HOME: "{{ datas_host.root_path }}"

- name: setting variables in task context
  set_fact:
    key_value: "true" # warning disable in vscode ( not needed for real)
    docker_machine_env_registry: "{{ docker_machine_env_exports.stdout | from_json }}"

- name: deploy k8s docker-machine
  include_role:
    name: kws_deploy_docker_context
  vars:
    home_path: "{{ datas_host.root_path }}"
    docker_machine_name: "{{ k8s_host.docker_machine_name }}"
    cpu_count: "{{ k8s_host.cpu_count }}"
    disk_size: "{{ k8s_host.disk_size }}"
    network_cidr: "{{ k8s_host.network_cidr }}"
    memory: "{{ k8s_host.memory }}"
    boot2docker_iso_url: "{{ k8s_host.boot2docker_iso_url }}"
    insecure_registry: "{{ docker_machine_env_registry.DOCKER_HOST_IP }}:{{ registry_host.registry_port }}"

- name: deploy k8s kind cluster
  include_role:
    name: kws_deploy_kind_cluster
  vars:
    home_path: "{{ datas_host.root_path }}"
    docker_machine_name: "{{ k8s_host.docker_machine_name }}"
    shared_folder: "{{ k8s_host.shared_folder }}"
