- name: "deploy {{ module_name }} module"
  include_role:
    name: kws_deploy_module
  vars:
    k8s_context: "{{ configs.host.k8s.context }}"
    namespace: kws-builder-git
    module_name: kws-builder-git-gogs
    chart_path: "{{ layer_path }}/chart/"
    helm_values: "{{ configs.builder.git.helm_values }}"

- name: check if gogs already configured
  stat:
    path: "{{ configs.core.datas.root_path }}/shared/kws-builder-git/gogs/conf/app.ini"
  register: gogs_app_ini_stat

- name: wait for gogs post-install available
  uri:
    url: "{{ configs.builder.git.gogs_values.app_url }}/install"
    follow_redirects: none
    method: GET
  register: ensure_gogs_ready
  until: ensure_gogs_ready.status == 200
  retries: 10
  delay: 5
  when:
    - "not gogs_app_ini_stat.stat.exists"

- name: gogs post install
  uri:
    url: "{{ configs.builder.git.gogs_values.app_url }}/install"
    method: POST
    body_format: form-urlencoded
    body: "{{ configs.builder.git.gogs_values }}"
    status_code: 302
  when:
    - "not gogs_app_ini_stat.stat.exists"
