- name: "{{ phase }} process"
  hosts: localhost
  vars:
    phase: deploy
  tasks:
    - name: "core layer"
      include_role:
        name: kws_phase_layer
      vars:
        group: core
        layer: "{{ item }}"
      with_items: "{{ layers.core }}"

    - name: "host layer"
      include_role:
        name: kws_phase_layer
      vars:
        group: host
        layer: "{{ item }}"
      with_items: "{{ layers.host }}"

    - name: "builder layer"
      include_role:
        name: kws_phase_layer
      vars:
        group: builder
        layer: "{{ item }}"
      with_items: "{{ layers.builder }}" 