# deploy process

- name: "datas-host layer"
  import_playbook: "../layers/datas-host/playbook/deploy.yaml"

- name: "k8s-host layer"
  import_playbook: "../layers/k8s-host/playbook/deploy.yaml"

- name: "dns-host layer"
  import_playbook: "../layers/dns-host/playbook/deploy.yaml"

- name: "k8s-cluster layer"
  import_playbook: "../layers/k8s-cluster/playbook/deploy.yaml"

- name: "builder-host layer"
  import_playbook: "../layers/builder-host/playbook/deploy.yaml"
