# install process

- name: "datas-host layer"
  import_playbook: "../layers/datas-host/playbook/install.yaml"

- name: "k8s-host layer"
  import_playbook: "../layers/k8s-host/playbook/install.yaml"

- name: "dns-host layer"
  import_playbook: "../layers/dns-host/playbook/install.yaml"

# - name: "k8s-cluster layer"
#   import_playbook: "../layers/k8s-cluster/playbook/install.yaml"
