- name: "{{ phase }} process"
  hosts: localhost
  vars:
    phase: undeploy
  roles:
    - role: kws_phase_layer
      layer: "builder-host"

    - role: kws_phase_layer
      layer: "k8s-cluster"

    - role: kws_phase_layer
      layer: "dns-host"

    - role: kws_phase_layer
      layer: "k8s-host"

    - role: kws_phase_layer
      layer: "registry-host"

    - role: kws_phase_layer
      layer: "docker-host"

    - role: kws_phase_layer
      layer: "datas-host"
