# undeploy process

# - name: "k8s-cluster layer"
#   import_playbook: "../layers/k8s-cluster/playbook/undeploy.yaml"
- name: "dns-host layer"
  import_playbook: "../layers/dns-host/playbook/undeploy.yaml"

- name: "k8s-host layer"
  import_playbook: "../layers/k8s-host/playbook/undeploy.yaml"

- name: "datas-host layer"
  import_playbook: "../layers/datas-host/playbook/undeploy.yaml"
