- name: "{{ phase }} process"
  hosts: localhost
  vars:
    phase: undeploy
  vars_prompt:
  tasks:
    - name: "builder layer"
      include_role:
        name: kws_phase_layer
      vars:
        group: builder
        layer: "{{ item }}"
      with_items: "{{ layers.builder | reverse | list }}"

    - name: "host layer"
      include_role:
        name: kws_phase_layer
      vars:
        group: host
        layer: "{{ item }}"
      with_items: "{{ layers.host | reverse | list }}"

    - name: "core layer"
      include_role:
        name: kws_phase_layer
      vars:
        group: core
        layer: "{{ item }}"
      with_items: "{{ layers.core | reverse | list }}"
