- name: "{{ phase }} process"
  hosts: localhost
  vars:
    phase: uninstall
  vars_prompt:
    - name: "remove_datas_root"
      prompt: "Are you sure to delete all your data root folder ({{ configs.core.datas.root_path }}) (yes/no)?"
      private: no

  tasks:
    - name: "host layer"
      include_role:
        name: kws_phase_layer
      vars:
        group: host
        layer: "{{ item }}"
      with_items: "{{ layers.host | reverse | list }}"

    - name: "core layer"
      include_role:
        name: kws_phase_layer
      vars:
        group: core
        layer: "{{ item }}"
      with_items: "{{ layers.core | reverse | list }}"
