- name: "{{ phase }} process"
  hosts: localhost
  vars:
    phase: uninstall
  vars_prompt:
    - name: "remove_datas_root"
      prompt: "Are you sure to delete all your data root folder ({{ datas_host.root_path }}) (yes/no)?"
      private: no
  roles:
    - role: kws_phase_layer
      layer: "builder-host"

    - role: kws_phase_layer
      layer: "k8s-cluster"

    - role: kws_phase_layer
      layer: "dns-host"

    - role: kws_phase_layer
      layer: "k8s-host"

    - role: kws_phase_layer
      layer: "registry-host"

    - role: kws_phase_layer
      layer: "docker-host"

    - role: kws_phase_layer
      layer: "datas-host"
      when:
        - "remove_datas_root | bool" 