- name: "deploy {{ module_name }} module"
  include_role:
    name: kws_deploy_module
  vars:
    home_path: "{{ datas_host.root_path }}"
    docker_machine_name: "{{ k8s_host.docker_machine_name }}"
    k8s_context: "{{ k8s_cluster.k8s_context }}"
    namespace: kw-builder-git
    module_name: kw-builder-git-gogs
    chart_path: "{{ module_path }}/chart/"
    helm_values: "{{ builder_host['kw-builder-git'].helm_values }}"

- name: check if gogs already configured
  stat:
    path: "{{ datas_host.root_path }}/shared/kw-builder-git/gogs/conf/app.ini"
  register: gogs_app_ini_stat

- name: wait for gogs post-install available
  uri:
    url: http://git.{{ dns_host.tld }}/install
    follow_redirects: none
    method: GET
  register: ensure_gogs_ready
  until: ensure_gogs_ready.status == 200
  retries: 6
  delay: 5
  when:
    - "not gogs_app_ini_stat.stat.exists"

- name: gogs post install
  uri:
    url: http://git.{{ dns_host.tld }}/install
    method: POST
    body_format: form-urlencoded
    body: "{{ builder_host['kw-builder-git'].gogs_values }}"
    status_code: 302
  when:
    - "not gogs_app_ini_stat.stat.exists"
