- name: deploy registry docker-machine
  include_role:
    name: kws_deploy_docker_context
  vars:
    home_path: "{{ datas_host.root_path }}"
    docker_machine_name: "{{ registry_host.docker_machine_name }}"
    cpu_count: "{{ registry_host.cpu_count }}"
    disk_size: "{{ registry_host.disk_size }}"
    network_cidr: "{{ registry_host.network_cidr }}"
    memory: "{{ registry_host.memory }}"
    boot2docker_iso_url: "{{ registry_host.boot2docker_iso_url }}"

- name: deploy registry container
  include_role:
    name: kws_deploy_docker_container
  vars:
    home_path: "{{ datas_host.root_path }}"
    docker_machine_name: "{{ registry_host.docker_machine_name }}"
    container:
      name: kw-registry-host
      image: registry:2
      ports: "--publish {{ registry_host.registry_port }}:5000"
      volumes: "-v {{ datas_host.root_path }}/registry:/var/lib/registry"
      env: ""