#global config
env_name: "dev"
datas_root: "/Users/krux/ws_dev_root"

## docker-stack values
docker_stack:  
  undeploy_reqs: true # don't undeploy base prerequirements for docker-machine  
  cpu_count: 2
  memory: 4096
  disk_size: 20000
  network_cidr: "192.168.99.1/24"
  #TODO: build my own boot2docker fork ( original source is deprecated , embedding kind )
  boot2docker_iso_url: "https://github.com/boot2docker/boot2docker/releases/download/v19.03.5/boot2docker.iso"
