- name: check for cluster
  command:
    argv:
      - kind
      - get
      - clusters
  register: clusters_list
  changed_when: no

- name: create {{ module_name }} namespace
  k8s:
    state: present
    context: "{{ k8s_context }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
        labels:
          app.kubernetes.io/name: "{{ namespace }}"
          app.kubernetes.io/instance: "{{ namespace }}"
          ws.krux.io/backup-include: "true"
  when: "env_name in clusters_list.stdout"

- name: create "temp" helm_values files for  {{ module_name }}"
  copy:
    content: "{{ helm_values | to_nice_yaml }}"
    dest: ./{{ module_name }}.helm_values.tmp.yaml
  when: "env_name in clusters_list.stdout"

- name: "installing/upgrading helm chart for {{ module_name }}"
  command:
    argv:
      - helm
      - upgrade
      - --install
      - --kube-context
      - "{{ k8s_context }}"
      - --wait
      - --timeout
      - 90s
      - --namespace
      - "{{ namespace }}"
      - -f
      - ./{{ module_name }}.helm_values.tmp.yaml
      - "{{ module_name }}"
      - "{{ chart_path }}"
  when: "env_name in clusters_list.stdout"

- name: delete "temp" helm_values files for  {{ module_name }}"
  file:
    path: ./{{ module_name }}.helm_values.tmp.yaml
    state: absent
  when: "env_name in clusters_list.stdout"
