- name: check if docker-machine {{ docker_machine_name }} exists
  shell: |
    docker-machine ls \
    --filter NAME={{ docker_machine_name }} \
    -f "."
  changed_when: no
  register: docker_machine_exists
  failed_when: no
  environment:
    HOME: "{{ home_path }}"

- name: remove docker-machine {{ docker_machine_name }} instance
  shell: "docker-machine rm {{ docker_machine_name }} -y"
  when:
    - docker_machine_exists.stdout is defined
    - "'.' in  docker_machine_exists.stdout"
  environment:
    HOME: "{{ home_path }}"
