- name: "{{ phase }} platform layer for {{ layer }}"
  include_role:
    name: kws_phase_platform_layer

- name: deploy k8s kind cluster
  include_role:
    name: kws_deploy_kind_cluster
  vars:
    home_path: "{{ configs.core.datas.root_path }}"
    shared_folder: "{{ configs.host.k8s.shared_folder }}"
    registry_container_name: "{{ configs.host.registry.container_name }}"
    registry_container_port: "{{ configs.host.registry.port }}"
 