# check docker-machine presence
- name: check if docker-machine already exists
  command:
    argv:
      - docker-machine
      - ls
      - --filter
      - NAME={{ env_name }}
      - -f
      - "."
  changed_when: no
  register: docker_machine_exists
  environment:
    HOME: "{{ datas_root }}"
# create docker-machine instance
- name: create docker-machine instance
  command:
    argv:
      - docker-machine
      - create
      - --engine-label
      - k-ws-env="{{ env_name }}"
      - --driver
      - virtualbox
      - --virtualbox-cpu-count
      - "{{ docker_stack.cpu_count }}"
      - --virtualbox-disk-size
      - "{{ docker_stack.disk_size }}"
      - --virtualbox-hostonly-cidr
      - "{{ docker_stack.network_cidr }}"
      - --virtualbox-memory
      - "{{ docker_stack.memory }}"
      - --virtualbox-boot2docker-url  
      - "{{ docker_stack.boot2docker_iso_url }}" 
      - "{{ env_name }}"
  when: "'.' not in  docker_machine_exists.stdout"
  environment:
    HOME: "{{ datas_root }}"