# install VirtualBox for docker-machine vbox driver
- name: install virtualbox for mac via homebrew (cask)
  homebrew_cask:
    name: virtualbox
    state: present
  register: install_vbox
- name: virtualbox launch after install
  command:
    argv:
      - open
      - /Applications/VirtualBox.app
  when: install_vbox.changed
- name: fail
  fail:
    msg: configure virtualbox before relaunching deployment
  when: install_vbox.changed
# install docker-cli
- name: "installing docker cli via brew"
  homebrew:
    name: docker
    state: present
- name: "link docker cli via brew"
  homebrew:
    name: docker
    state: linked
# install docker-compose cli
- name: "installing docker-compose cli via brew"
  homebrew:
    name: docker-compose
    state: present
- name: "link docker-compose cli via brew"
  homebrew:
    name: docker-compose
    state: linked
# install docker-machine
- name: "installing docker-machine via brew"
  homebrew:
    name: docker-machine
    state: present

