# check docker-machine presence
- name: check if docker-machine {{ docker_machine_name }} already exists
  command:
    argv:
      - docker-machine
      - ls
      - --filter
      - NAME={{ docker_machine_name }}
      - -f
      - "."
  changed_when: no
  register: docker_machine_exists
  environment:
    HOME: "{{ home_path }}"

# create docker-machine instance
- name: create docker-machine instance {{ docker_machine_name }}
  shell: |    
      docker-machine create \
      --engine-label k-ws-env="{{ env_name }}" \
      {% if insecure_registry %}
      --engine-insecure-registry "{{ insecure_registry }}" \
      {% endif %}
      --driver virtualbox \
      --virtualbox-cpu-count "{{ cpu_count }}" \
      --virtualbox-disk-size "{{ disk_size }}" \
      --virtualbox-hostonly-cidr "{{ network_cidr }}" \
      --virtualbox-memory "{{ memory }}" \
      --virtualbox-boot2docker-url "{{ boot2docker_iso_url }}" \
      "{{ docker_machine_name }}"
  when: "'.' not in  docker_machine_exists.stdout"
  environment:
    HOME: "{{ home_path }}"
