#global config
env_name: "example"
user_home_path: "{{ lookup('env','HOME') }}"

datas_host:
  root_path: "{{ user_home_path }}/kws_{{ env_name }}_datas"

dns_host:
  tld: "{{ env_name }}.kws"

k8s_host:
  shared_folder: "{{ user_home_path }}/kws_{{ env_name }}_datas/shared"
  cpu_count: 2 # more than one is recommanded for best performances
  memory: 4096
  disk_size: 20000
  network_cidr: "192.168.99.1/24"
  #TODO: build my own boot2docker fork ( original source is deprecated and not working properly with 19.03.5 latest release )
  boot2docker_iso_url: "https://github.com/boot2docker/boot2docker/releases/download/v19.03.5/boot2docker.iso"

k8s_cluster:
  k8s_context: "kind-{{ env_name }}"

builder_host:
  kw-builder-git:
    helm_values:
      containerPort: 3000
      mountPath: /data
      replicaCount: 1
      image:
        repository: gogs/gogs
        pullPolicy: IfNotPresent
        tag: "latest"
     
      ingress:
        enabled: true
        annotations: {}
        hosts:
          - host: git.example.kws
            paths:
              - /
        tls: []
      persistence:
        enabled: true
        storageClass: "local-path"
        accessMode: ReadWriteOnce
        size: 10Gi
        hostPath: "/kws_datas/kw-builder-git"
    gogs_values: 
      db_type: SQLite3
      db_host:
      db_user:
      db_passwd:
      db_name: gogs
      ssl_mode: disable
      db_path: /data/git/gogs.db
      app_name: kws-git
      repo_root_path: /data/git/gogs-repositories
      run_user: git
      domain: localhost
      ssh_port:
      http_port: 3000
      app_url: http://git.{{ dns_host.tld }}
      log_root_path: /data/git/log
      smtp_host:
      smtp_from:
      smtp_user:
      smtp_passwd:
      disable_registration: on
      admin_name: gogs
      admin_passwd: changeme
      admin_confirm_passwd: changeme
      admin_email: gogs@example.kws
