#global config
env_name: "example"
user_home_path: "{{ lookup('env','HOME') }}"
host_ip: 127.0.0.1
host_dns: "{{ env_name }}.kws"
layers:
  core:
    # []
    - datas
    - docker
    - dns
    - certs
  host:
    #[]
    - registry
    - k8s
    - ingress
  builder:
    # []
    - git
    - ide

configs:
  core:
    datas:
      root_path: "{{ user_home_path }}/kws_{{ env_name }}_datas"
    dns:
      tld: "{{ host_dns }}"
      use_dnsmasq: true
    docker:
      install_docker: no # set to yes if you want docker to be install for current platform (if supported)
    certs:
      passphrase: changeme
      expiration: "+350d"
      csr_infos:
        country_name: FR
        organization_name: "k-workspace {{ env_name }}"
        organizational_unit_name: "{{ env_name }} local Certificate Authority"
        state_or_province_name: Ile-de-France
        locality_name: Paris
        email_address: admin@{{ host_dns }}
  host:
    registry:
      port: 5000
      container_name: "kws-{{ env_name }}-registry"
    k8s:
      shared_folder: "{{ user_home_path }}/kws_{{ env_name }}_datas/shared"
      context: "kind-{{ env_name }}"
  builder:
    git:
      helm_values:
        containerPort: 3000
        mountPath: /data
        replicaCount: 1
        image:
          repository: gogs/gogs
          pullPolicy: IfNotPresent
          tag: "latest"

        ingress:
          enabled: true
          annotations: {}
          hosts:
            - host: "git.{{ host_dns }}"
              paths:
                - /
          tls:
            - hosts:
                - git.{{ host_dns }}
        persistence:
          enabled: true
          storageClass: "local-path"
          accessMode: ReadWriteOnce
          size: 10Gi
          hostPath: "/kws_datas/kws-builder-git"
      gogs_values:
        db_type: SQLite3
        db_host:
        db_user:
        db_passwd:
        db_name: gogs
        ssl_mode: disable
        db_path: /data/git/gogs.db
        app_name: kws-git
        repo_root_path: /data/git/gogs-repositories
        run_user: git
        domain: localhost
        ssh_port:
        http_port: 3000
        app_url: https://git.{{ host_dns}}
        log_root_path: /data/git/log
        smtp_host:
        smtp_from:
        smtp_user:
        smtp_passwd:
        disable_registration: on
        admin_name: gogs
        admin_passwd: changeme
        admin_confirm_passwd: changeme
        admin_email: gogs@example.kws
    ide:
      helm_values:
        replicaCount: 1
        image:
          registry: localhost:5000
          name: "{{ env_name }}/kws-builder-ide"
          pullPolicy: IfNotPresent
          tag: "latest"
        container:
          containerPort: 8443
          env:
            - name: PROXY_DOMAIN
              value: ide.example.kws
            - name: PASSWORD
              value: changeme
            - name: SUDO_PASSWORD
              value: changeme
            - name: TZ
              value: Europe/Paris
            - name: PUID
              value: 1000
            - name: PGID
              value: 1000
        ingress:
          enabled: true
          annotations:
            {}
            # kubernetes.io/ingress.class: nginx
            # kubernetes.io/tls-acme: "true"
          hosts:
            - host: ide.{{ host_dns }}
              paths:
                - /
          tls:
            - hosts:
                - ide.{{ host_dns }}
        persistence:
          enabled: true
          storageClass: "local-path"
          accessMode: ReadWriteOnce
          size: 10Gi
          hostPath: "/kws_datas/kws-builder-ide"
          mountPath: /config
        securityContext:
          allowPrivilegeEscalation: true
          runAsGroup: 8443
