kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  apiServerPort: 6443
  apiServerAddress: "{{ docker_machine_env.DOCKER_HOST_IP }}"
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # HTTP
      - containerPort: 80
        hostPort: 80
        listenAddress: "0.0.0.0"
        protocol: TCP
      # HTTPS
      - containerPort: 443
        hostPort: 443
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: worker
    extraMounts:
      - hostPath: "{{ shared_folder }}"
        containerPath: /kws_datas
  - role: worker
    extraMounts:
      - hostPath: "{{ shared_folder }}"
        containerPath: /kws_datas