kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:{{ configs.host.registry.port }}"]
    endpoint = ["http://{{ configs.host.registry.container_name  }}:{{ configs.host.registry.port  }}"]
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  apiServerPort: 6443
  apiServerAddress: "{{ host_ip }}"
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # HTTP
      - containerPort: 80
        hostPort: 80
        listenAddress: "{{ host_ip }}"
        protocol: TCP
      # HTTPS
      - containerPort: 443
        hostPort: 443
        listenAddress: "{{ host_ip }}"
        protocol: TCP
  - role: worker
    extraMounts:
      - hostPath: "{{ shared_folder }}"
        containerPath: /kws_datas
  - role: worker
    extraMounts:
      - hostPath: "{{ shared_folder }}"
        containerPath: /kws_datas