# get docker_host env variable
# FIXME: rewrite in pure-ansible
- shell: "sh scripts/extract-docker-env-var.sh {{ env_name }}"
  register: docker_machine_env_exports
  changed_when: no
  environment:
    HOME: "{{ datas_root }}"

- name: setting variables in task context
  set_fact:
    key_value: "true" # warning disable in vscode ( not needed for real)
    docker_machine_env: "{{ docker_machine_env_exports.stdout | from_json }}"

- name: check for cluster
  command:
    cmd: kind get clusters
  changed_when: false
  register: clusters_list
  environment:
    HOME: "{{ datas_root }}"
    DOCKER_CERT_PATH: "{{ docker_machine_env.DOCKER_CERT_PATH }}"
    DOCKER_HOST: "{{ docker_machine_env.DOCKER_HOST }}"
    DOCKER_MACHINE_NAME: "{{ docker_machine_env.DOCKER_MACHINE_NAME }}"
    DOCKER_TLS_VERIFY: "{{ docker_machine_env.DOCKER_TLS_VERIFY }}"

- name: create data directory
  file:
    state: directory
    recurse: yes
    path: "{{ k8s_host.shared_folder }}"
    access_time: now

- name: prepare kind cluster config
  template:
    src: ./templates/kind-config.tpl.yaml
    dest: ./templates/kind-config.yaml
  when: "'No kind clusters found' in clusters_list.stderr"

- name: create kind cluster
  command:
    argv:
      - kind
      - create
      - cluster
      - --name
      - "{{ env_name }}"
      - --config
      - ./templates/kind-config.yaml
  when: "'No kind clusters found' in clusters_list.stderr"
  environment:
    HOME: "{{ datas_root }}"
    DOCKER_CERT_PATH: "{{ docker_machine_env.DOCKER_CERT_PATH }}"
    DOCKER_HOST: "{{ docker_machine_env.DOCKER_HOST }}"
    DOCKER_MACHINE_NAME: "{{ docker_machine_env.DOCKER_MACHINE_NAME }}"
    DOCKER_TLS_VERIFY: "{{ docker_machine_env.DOCKER_TLS_VERIFY }}"
    
- name: deleting kind-config template result
  file:
    path: ./templates/kind-config.yaml
    state: absent
  when: "'No kind clusters found' in clusters_list.stderr"

- name: setup kind kubeconfig
  command:
    cmd: kind export kubeconfig --name {{ env_name }}
  changed_when: false
  environment:
    HOME: "{{ datas_root }}"
    DOCKER_CERT_PATH: "{{ docker_machine_env.DOCKER_CERT_PATH }}"
    DOCKER_HOST: "{{ docker_machine_env.DOCKER_HOST }}"
    DOCKER_MACHINE_NAME: "{{ docker_machine_env.DOCKER_MACHINE_NAME }}"
    DOCKER_TLS_VERIFY: "{{ docker_machine_env.DOCKER_TLS_VERIFY }}"
    

