# get docker_host env variable
# FIXME: rewrite in pure-ansible
- name: extracting docker-machine env vars
  shell: "sh ./scripts/extract-docker-machine-vars.sh {{ env_name }}"
  register: docker_machine_env_exports
  changed_when: no
  environment:
    HOME: "{{ datas_host.root_path }}"
- name: setting variables in task context
  set_fact:
    key_value: "true" # warning disable in vscode ( not needed for real)
    docker_machine_env: "{{ docker_machine_env_exports.stdout | from_json }}"

# Undeploying kind cluster
- name: check for cluster
  command:
    argv:
      - kind
      - get
      - clusters
  register: clusters_list
  environment:
    HOME: "{{ datas_host.root_path }}"
    DOCKER_CERT_PATH: "{{ docker_machine_env.DOCKER_CERT_PATH }}"
    DOCKER_HOST: "{{ docker_machine_env.DOCKER_HOST }}"
    DOCKER_MACHINE_NAME: "{{ docker_machine_env.DOCKER_MACHINE_NAME }}"
    DOCKER_TLS_VERIFY: "{{ docker_machine_env.DOCKER_TLS_VERIFY }}"
- name: delete kind cluster
  command:
    argv:
      - kind
      - delete
      - cluster
      - --name
      - "{{ env_name }}"
  when: "{{ env_name in clusters_list.stdout }}"
  environment:
    HOME: "{{ datas_host.root_path }}"
    DOCKER_CERT_PATH: "{{ docker_machine_env.DOCKER_CERT_PATH }}"
    DOCKER_HOST: "{{ docker_machine_env.DOCKER_HOST }}"
    DOCKER_MACHINE_NAME: "{{ docker_machine_env.DOCKER_MACHINE_NAME }}"
    DOCKER_TLS_VERIFY: "{{ docker_machine_env.DOCKER_TLS_VERIFY }}"

# check docker-machine presence
- name: check if docker-machine exists
  command:
    argv:
      - docker-machine
      - ls
      - --filter
      - NAME={{ env_name }}
      - -f
      - "."
  changed_when: no
  register: docker_machine_exists
  failed_when: no
  environment:
    HOME: "{{ datas_host.root_path }}"

# remove docker-machine instance
- name: remove docker-machine instance
  command:
    argv:
      - docker-machine
      - rm
      - "{{ env_name }}"
      - -y
  when:
    - docker_machine_exists.stdout is defined
    - "'.' in  docker_machine_exists.stdout"
  environment:
    HOME: "{{ datas_host.root_path }}"
