- name: check for kind
  shell: which kind
  failed_when: no
  changed_when: no
  register: kind_present

- name: get local cluster kind
  shell: kind get clusters
  changed_when: false
  register: clusters_list
  when:
    - "'kind' in kind_present.stdout"
- name: delete kind cluster
  command:
    argv:
      - kind
      - delete
      - cluster
      - --name
      - "{{ env_name }}"
  when:
    - "'kind' in kind_present.stdout"
    - "env_name in clusters_list.stdout"

- name: remove kind context
  command:
    cmd: kubectl config unset contexts.kind-{{ env_name }}
  when:
    - "'kind' in kind_present.stdout"
    - "env_name not in clusters_list.stdout"
