- name: extracting docker-machine env vars
  shell: "sh ./roles/common/files/extract-docker-machine-vars.sh {{ docker_machine_name }}"
  register: docker_machine_env_exports
  changed_when: no
  environment:
    HOME: "{{ home_path }}"

- name: setting variables in task context
  set_fact:
    key_value: "true" # warning disable in vscode ( not needed for real)
    docker_machine_env: "{{ docker_machine_env_exports.stdout | from_json }}"

- name: get local cluster kind
  shell: kind get clusters
  changed_when: false
  register: clusters_list
  environment:
    HOME: "{{ datas_host.root_path }}"
    DOCKER_CERT_PATH: "{{ docker_machine_env.DOCKER_CERT_PATH }}"
    DOCKER_HOST: "{{ docker_machine_env.DOCKER_HOST }}"
    DOCKER_MACHINE_NAME: "{{ docker_machine_env.DOCKER_MACHINE_NAME }}"
    DOCKER_TLS_VERIFY: "{{ docker_machine_env.DOCKER_TLS_VERIFY }}"

- name: delete kind cluster
  command:
    argv:
      - kind
      - delete
      - cluster
      - --name
      - "{{ env_name }}"
  when: "env_name in clusters_list.stdout"
  environment:
    HOME: "{{ datas_host.root_path }}"
    DOCKER_CERT_PATH: "{{ docker_machine_env.DOCKER_CERT_PATH }}"
    DOCKER_HOST: "{{ docker_machine_env.DOCKER_HOST }}"
    DOCKER_MACHINE_NAME: "{{ docker_machine_env.DOCKER_MACHINE_NAME }}"
    DOCKER_TLS_VERIFY: "{{ docker_machine_env.DOCKER_TLS_VERIFY }}"
