- name: get local cluster kind
  shell: kind get clusters
  changed_when: false
  register: clusters_list

- name: delete kind cluster
  command:
    argv:
      - kind
      - delete
      - cluster
      - --name
      - "{{ env_name }}"
  when: "env_name in clusters_list.stdout"

- name: remove kind context
  command:
    cmd: kubectl config unset contexts.kind-{{ env_name }}
  when: "env_name not in clusters_list.stdout"

